from __future__ import annotations

import json
from pathlib import Path


DEFAULT_THRESHOLDS = {
    "service": {
        "host": "127.0.0.1",
        "port": 8091,
        "max_concurrent_runs": 2,
        "page_worker_max_workers": 4,
        "ocr_max_workers": 4,
        "opencv_num_threads": 1,
        "tesseract_omp_thread_limit": 1,
        "tesseract_omp_num_threads": 1,
        "performance_sample_interval_seconds": 0.5,
    },
    "review_engine": {
        "enabled": True,
        "auto_dispatch_enabled": True,
        "host": "127.0.0.1",
        "port": 8092,
        "max_concurrent_runs": 1,
        "candidate_review_states": ["review_required", "quarantined"],
        "candidate_sort_lanes": ["table_specialist", "weak_fallback"],
        "candidate_layout_types": ["table", "mixed", "form"],
        "cardinal_rotation_candidates": [90, 270],
        "max_pages_per_run": 12,
        "table_region_minimum": 4,
        "render_dpi": 300,
        "horizontal_kernel_divisor": 28,
        "vertical_kernel_divisor": 28,
        "table_min_width": 120,
        "table_min_height": 60,
        "table_min_area": 6000,
        "line_min_span_ratio": 0.45,
        "line_thickness_limit": 18,
        "line_merge_tolerance_pixels": 10,
        "grid_min_row_boundaries": 3,
        "grid_min_col_boundaries": 3,
        "cell_min_width": 18,
        "cell_min_height": 12,
        "cell_padding_pixels": 4,
        "cell_blank_dark_ratio_threshold": 0.001,
        "table_max_cells": 400,
        "ocr_psm": 7,
        "ocr_fallback_psm": 6,
        "copyback_subdir": "review_engine",
    },
    "janitor": {
        "keep_outbox_folders": 1,
        "require_success_marker": True,
        "purge_work_runs": True,
        "purge_logs_runs": True,
        "purge_manifest_pages": True,
        "purge_manifest_regions": True,
        "purge_review_runtime": True,
        "purge_run_manifests": True,
        "purge_run_manifest_locks_and_backups": True,
        "keep_manifests_for_kept_outbox_runs": False,
        "purge_inbox": False,
    },
    "state_machine": {
        "blank_separator_alnum_threshold": 24,
        "blank_separator_region_threshold": 12,
        "pre_ocr_blank_dark_ratio_threshold": 0.0002,
        "pre_ocr_blank_max_regions": 24,
        "handwriting_dense_region_threshold": 40,
        "handwriting_dense_text_region_threshold": 20,
        "table_region_threshold": 2,
        "table_account_code_threshold": 4,
        "table_numeric_line_threshold": 6,
        "table_currency_threshold": 4,
        "table_max_paragraph_lines": 2,
        "table_short_line_ratio_threshold": 0.55,
        "table_dominant_account_code_threshold": 8,
        "table_dominant_numeric_line_threshold": 20,
        "table_dominant_currency_threshold": 20,
        "sparse_table_region_threshold": 20,
        "sparse_table_max_lines": 18,
        "rotated_table_region_threshold": 4,
        "rotated_table_skew_threshold": 12.0,
        "powerpoint_bullet_threshold": 4,
        "powerpoint_short_line_threshold": 96,
        "powerpoint_max_alnum": 450,
        "powerpoint_max_currency_hits": 2,
        "powerpoint_numeric_line_threshold": 2,
        "prose_long_line_threshold": 90,
        "agenda_continuation_list_threshold": 4,
        "government_form_field_label_threshold": 4,
        "government_form_signature_threshold": 2,
        "government_form_header_line_window": 8,
        "contract_dominant_line_threshold": 8,
        "contract_over_form_margin": 0.02,
        "support_subtype_min_score": 0.58,
        "support_subtype_header_weight": 0.12,
        "support_subtype_body_weight": 0.06,
        "support_subtype_body_match_threshold": 2,
        "family_inference_neighbor_distance": 2,
        "suspicion_close_score_margin": 0.08,
        "suspicion_low_confidence_threshold": 0.70,
        "suspicion_very_low_confidence_threshold": 0.55,
        "suspicion_dense_blank_region_threshold": 20,
        "suspicion_report_threshold": 0.35,
        "finance_prose_line_threshold": 3,
        "finance_prose_max_numeric_lines": 3,
        "finance_prose_max_currency_hits": 2,
        "financial_summary_table_line_threshold": 18,
        "financial_summary_table_currency_threshold": 6,
        "financial_context_block_table_regions": 4,
        "financial_context_block_skew_threshold": 12.0,
        "low_text_attachment_alnum_threshold": 80,
        "context_anchor_score_threshold": 0.72,
        "context_max_anchor_distance": 6,
        "context_sandwich_distance": 2,
        "context_agenda_min_list_lines": 3,
        "context_agenda_min_marker_hits": 1,
        "context_minutes_min_motion_vote_lines": 1,
        "context_reference_min_section_lines": 1,
        "context_legislative_min_marker_hits": 1,
        "context_contract_min_semantic_hits": 2,
        "context_contract_min_contract_lines": 1,
        "context_contract_min_section_lines": 1,
        "context_contract_min_clause_headings": 1,
        "context_finance_min_lexical_lines": 1,
        "context_finance_min_currency_hits": 1,
        "context_finance_min_account_codes": 1,
        "context_finance_min_numeric_lines": 4,
        "context_form_min_body_hits": 1,
    },
    "extraction": {
        "native_text_quality_threshold": 0.85,
        "ocr_dpi": 300,
        "render_dpi": 300,
        "ocr_candidate_max_dim": 0,
        "persist_region_manifests": False,
        "grayscale": True,
        "cardinal_orientation_trigger_skew_threshold": 6.0,
        "cardinal_orientation_skew_margin": 2.5,
        "cardinal_orientation_score_margin": 18.0,
        "cardinal_orientation_projection_trigger_margin": 10.0,
        "cardinal_orientation_projection_max_dim": 1400,
        "cardinal_orientation_ocr_max_dim": 1400,
        "cardinal_orientation_use_ocr_confirmation": True,
        "cardinal_orientation_blank_dark_ratio_floor": 0.001,
        "geometry_refine_scoring_max_dim": 1600,
        "geometry_refine_blank_dark_ratio_floor": 0.001,
        "geometry_refine_skip_below_abs_angle": 0.4,
        "geometry_refine_max_angle_degrees": 18.0,
        "geometry_refine_coarse_window_degrees": 6.0,
        "geometry_refine_coarse_step_degrees": 1.0,
        "geometry_refine_fine_window_degrees": 1.25,
        "geometry_refine_fine_step_degrees": 0.25,
        "geometry_refine_min_score_improvement": 0.5,
        "geometry_refine_residual_threshold": 0.9,
        "geometry_refine_max_passes": 2,
        "ocr_retry_alnum_threshold": 24,
        "ocr_retry_skew_alnum_threshold": 320,
        "ocr_retry_table_threshold": 3,
        "ocr_retry_skew_threshold": 8.0,
    },
    "page_types": {
        "enabled": [
            "blank_separator",
            "agenda",
            "minutes",
            "reference_or_procedure",
            "legislative_prose",
            "contract_or_agreement",
            "financial_report",
            "government_form",
            "invoice",
            "table_or_mixed_layout",
            "generic_prose",
            "powerpoint",
        ],
        "reserved": ["powerpoint"],
    },
}


def _deep_merge(base: dict, updates: dict) -> dict:
    merged = dict(base)
    for key, value in updates.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge(merged[key], value)
        else:
            merged[key] = value
    return merged


def load_thresholds(base_dir: Path) -> dict:
    config_path = base_dir / "config" / "thresholds.json"
    with open(config_path, "r", encoding="utf-8") as f:
        file_thresholds = json.load(f)
    return _deep_merge(DEFAULT_THRESHOLDS, file_thresholds)


def get_service_settings(thresholds: dict) -> dict:
    return thresholds.get("service", {})
